#!/usr/bin/env python3

"""Filter Jupyter notebook cells by tag."""

import argparse
import sys

import nbformat
import black

def main() -> None:
    """Filter Jupyter notebook cells by tag."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-i",
        "--input",
        nargs="?",
        type=argparse.FileType("r"),
        default=sys.stdin,
        help="input file",
    )
    parser.add_argument(
        "-o",
        "--output",
        nargs="?",
        type=argparse.FileType("w"),
        default=sys.stdout,
        help="output file",
    )
    parser.add_argument(
        "-l",
        "--length",
        nargs="?",
        type=int,
        default=79,
        help="black line length",
    )
    args = parser.parse_args()
    notebook = nbformat.read(args.input, as_version=nbformat.NO_CONVERT)
    formatted_cells = []
    for cell in notebook["cells"]:

        if cell["cell_type"] == "code":
            source = ''.join(cell["source"])
            formatted_source = black.format_str(source, args.length)
            cell["source"] = formatted_source.splitlines()
        
        formatted_cells.append(cell)

    notebook["cells"] = formatted_cells
    nbformat.write(notebook, args.output)


if __name__ == "__main__":
    main()
